version: '3'

services:
  loraficationd:
    build:
      context: .
      dockerfile: ./cmd/loraficationd/deploy/Dockerfile
    ports:
      - "9000:9000"
    environment:
      - LORAFICATION_LOG_LEVEL
      - LORAFICATION_PORT
      - LORAFICATION_DB_USER
      - LORAFICATION_DB_PASS
      - LORAFICATION_DB_NAME
      - LORAFICATION_DB_HOST
      - LORAFICATION_DB_PORT
      - LORAFICATION_SMTP_HOST
      - LORAFICATION_SMTP_PORT
      - LORAFICATION_SMTP_USER
      - LORAFICATION_SMTP_PASS
      - LORAFICATION_READ_TIMEOUT
      - LORAFICATION_WRITE_TIMEOUT
      - LORAFICATION_SHUTDOWN_TIMEOUT
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:13.0
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lorafication
    restart: on-failure